global using System.Collections.Generic;
global using System.Data;
global using System.Dynamic;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Forms;
global using CommunityToolkit.ReportEditor.Model.Models;
global using Dapper;
global using MasterNeverDown.ReportStudio.ToolBar.LangRes;
global using Npgsql;
global using unvell.ReoGrid;
global using unvell.ReoGrid.IO;
global using UserControl = System.Windows.Controls.UserControl;
global using System.Windows.Documents;
global using AakStudio.Shell.UI.Showcase.Commands;
global using AakStudio.Shell.UI.Showcase.Shell;
global using Label = System.Windows.Controls.Label;
global using System.Windows.Input;
global using Control = System.Windows.Controls.Control;
global using System;
global using System.Globalization;
global using System.Windows.Media;
global using unvell.ReoGrid.Graphics;
global using Button = System.Windows.Controls.Button;
global using System.Windows.Data;
global using AakStudio.Shell.UI.Showcase.ViewModels.Collection;
global using Binding = System.Windows.Data.Binding;
global using Point = unvell.ReoGrid.Graphics.Point;
global using unvell.ReoGrid.Events;
global using System;
global using System.Windows.Threading;
global using Application = System.Windows.Application;
global using MessageBox = System.Windows.MessageBox;
global using System;
global using AakStudio.Shell.UI.Showcase.ViewModels;
global using System;
global using System.Collections.ObjectModel;
global using AakStudio.Shell.UI.Showcase.Shell;
global using AakStudio.Shell.UI.Showcase.ViewModels.Collection;
global using AakStudio.Shell.UI.Showcase.ViewModels.Interfaces;
global using AakStudio.Shell.UI.Showcase.Views;
global using System;
global using System.Windows.Input;
global using ComboBox = System.Windows.Controls.ComboBox;
global using InputType = CommunityToolkit.ReportEditor.Model.Models.InputType;
global  using AakStudio.Shell.UI.Showcase.ControlViews;
global  using System.Reflection;
global  using System.Windows.Controls.Primitives;
global  using CommunityToolkit.Mvvm.ComponentModel;
