//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterNeverDown.ReportStudio.ToolBar.LangRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterNeverDown.ReportStudio.ToolBar.LangRes.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string AlignmentPage_Degrees {
            get {
                return ResourceManager.GetString("AlignmentPage_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Horizontal:.
        /// </summary>
        public static string AlignmentPage_Horizontal {
            get {
                return ResourceManager.GetString("AlignmentPage_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Indent:.
        /// </summary>
        public static string AlignmentPage_Indent {
            get {
                return ResourceManager.GetString("AlignmentPage_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string AlignmentPage_Orientation {
            get {
                return ResourceManager.GetString("AlignmentPage_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text alignment.
        /// </summary>
        public static string AlignmentPage_Text_Alignment {
            get {
                return ResourceManager.GetString("AlignmentPage_Text_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text control.
        /// </summary>
        public static string AlignmentPage_Text_Control {
            get {
                return ResourceManager.GetString("AlignmentPage_Text_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vertical:.
        /// </summary>
        public static string AlignmentPage_Vertical {
            get {
                return ResourceManager.GetString("AlignmentPage_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wrap text.
        /// </summary>
        public static string AlignmentPage_Wrap_Text {
            get {
                return ResourceManager.GetString("AlignmentPage_Wrap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Appearance Editor.
        /// </summary>
        public static string AppearanceEditor_Caption {
            get {
                return ResourceManager.GetString("AppearanceEditor_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export C#.
        /// </summary>
        public static string AppearanceEditor_Export_CSharp {
            get {
                return ResourceManager.GetString("AppearanceEditor_Export_CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VB.NET.
        /// </summary>
        public static string AppearanceEditor_Export_VBNET {
            get {
                return ResourceManager.GetString("AppearanceEditor_Export_VBNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Highlight:.
        /// </summary>
        public static string AppearanceEditor_Highlight {
            get {
                return ResourceManager.GetString("AppearanceEditor_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Main:.
        /// </summary>
        public static string AppearanceEditor_Main {
            get {
                return ResourceManager.GetString("AppearanceEditor_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to &amp;Default.
        /// </summary>
        public static string AppearanceEditor_Reset_To_Default {
            get {
                return ResourceManager.GetString("AppearanceEditor_Reset_To_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Border &amp;Width:.
        /// </summary>
        public static string AppearanceEditor_Selection_Border_Width {
            get {
                return ResourceManager.GetString("AppearanceEditor_Selection_Border_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &amp;System Highlight Color.
        /// </summary>
        public static string AppearanceEditor_Use_System_Highligh_Color {
            get {
                return ResourceManager.GetString("AppearanceEditor_Use_System_Highligh_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string BorderPage_Line {
            get {
                return ResourceManager.GetString("BorderPage_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Presets.
        /// </summary>
        public static string BorderPage_Presets {
            get {
                return ResourceManager.GetString("BorderPage_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Style:.
        /// </summary>
        public static string BorderPage_Style {
            get {
                return ResourceManager.GetString("BorderPage_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string Btn_New {
            get {
                return ResourceManager.GetString("Btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Capation {
            get {
                return ResourceManager.GetString("Capation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string caption {
            get {
                return ResourceManager.GetString("caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string CellBody {
            get {
                return ResourceManager.GetString("CellBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection:.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string controls {
            get {
                return ResourceManager.GetString("controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Merge.
        /// </summary>
        public static string CtxMenu_Cell_Merge {
            get {
                return ResourceManager.GetString("CtxMenu_Cell_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unmerge.
        /// </summary>
        public static string CtxMenu_Cell_Unmerge {
            get {
                return ResourceManager.GetString("CtxMenu_Cell_Unmerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string CtxMenu_Col_Clear_Filter {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Clear_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &amp;Width....
        /// </summary>
        public static string CtxMenu_Col_Column_Width {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Column_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Columns.
        /// </summary>
        public static string CtxMenu_Col_Delete_Columns {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Delete_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filter.
        /// </summary>
        public static string CtxMenu_Col_Filter {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert Columns.
        /// </summary>
        public static string CtxMenu_Col_Insert_Columns {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Insert_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default Width.
        /// </summary>
        public static string CtxMenu_Col_Reset_To_Default_Width {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Reset_To_Default_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Rows.
        /// </summary>
        public static string CtxMenu_Row_Delete_Rows {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Delete_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert Rows.
        /// </summary>
        public static string CtxMenu_Row_Insert_Rows {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Insert_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default Height.
        /// </summary>
        public static string CtxMenu_Row_Reset_to_Default_Height {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Reset_to_Default_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row &amp;Height....
        /// </summary>
        public static string CtxMenu_Row_Row_Height {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Row_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Format.
        /// </summary>
        public static string Data_Format {
            get {
                return ResourceManager.GetString("Data_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _dataSourceContext不能为空.
        /// </summary>
        public static string datasource_cant_null {
            get {
                return ResourceManager.GetString("datasource_cant_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name.
        /// </summary>
        public static string DefineNamedRange_Caption {
            get {
                return ResourceManager.GetString("DefineNamedRange_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Comment:.
        /// </summary>
        public static string DefineNamedRange_Comment {
            get {
                return ResourceManager.GetString("DefineNamedRange_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Name:.
        /// </summary>
        public static string DefineNamedRange_Name {
            get {
                return ResourceManager.GetString("DefineNamedRange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Range:.
        /// </summary>
        public static string DefineNamedRange_Range {
            get {
                return ResourceManager.GetString("DefineNamedRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Background Color:.
        /// </summary>
        public static string FillPage_Background_Color {
            get {
                return ResourceManager.GetString("FillPage_Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill &amp;Pattern.
        /// </summary>
        public static string FillPage_Fill_Pattern {
            get {
                return ResourceManager.GetString("FillPage_Fill_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pattern &amp;Color.
        /// </summary>
        public static string FillPage_Fill_Pattern_Color {
            get {
                return ResourceManager.GetString("FillPage_Fill_Pattern_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pattern &amp;Style.
        /// </summary>
        public static string FillPage_Fill_Pattern_Style {
            get {
                return ResourceManager.GetString("FillPage_Fill_Pattern_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV File(*.csv)|*.csv|Text file(*.txt)|*.txt|All files(*.*)|*.*.
        /// </summary>
        public static string Filter_Export_As_CSV {
            get {
                return ResourceManager.GetString("Filter_Export_As_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Files(*.xlsx;*.csv;*.rgf)|*.xlsx;*.csv;*.rgf|ReoGrid XML Format(*.rgf)|*.rgf|Excel 2007(*.xlsx)|*.xlsx|CSV File(*.csv)|*.csv|All Files(*.*)|*.*.
        /// </summary>
        public static string Filter_Load_File {
            get {
                return ResourceManager.GetString("Filter_Load_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel 2007(*.xlsx)|*.xlsx|ReoGrid XML Format(*.rgf)|*.rgf|CSV File(*.csv)|*.csv|All Files(*.*)|*.*.
        /// </summary>
        public static string Filter_Save_File {
            get {
                return ResourceManager.GetString("Filter_Save_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Cells.
        /// </summary>
        public static string FormatPage_Caption {
            get {
                return ResourceManager.GetString("FormatPage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Category:.
        /// </summary>
        public static string FormatPage_Category {
            get {
                return ResourceManager.GetString("FormatPage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decimal Places:.
        /// </summary>
        public static string FormatPage_Decimal_Places {
            get {
                return ResourceManager.GetString("FormatPage_Decimal_Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Locale (location):.
        /// </summary>
        public static string FormatPage_Locale {
            get {
                return ResourceManager.GetString("FormatPage_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Negative numbers:.
        /// </summary>
        public static string FormatPage_Negative_Numbers {
            get {
                return ResourceManager.GetString("FormatPage_Negative_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pattern:.
        /// </summary>
        public static string FormatPage_Pattern {
            get {
                return ResourceManager.GetString("FormatPage_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Symbol:.
        /// </summary>
        public static string FormatPage_Symbol {
            get {
                return ResourceManager.GetString("FormatPage_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Type:.
        /// </summary>
        public static string FormatPage_Type {
            get {
                return ResourceManager.GetString("FormatPage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Use 1000 Separator ({0}).
        /// </summary>
        public static string FormatPage_Use_1000_Separator {
            get {
                return ResourceManager.GetString("FormatPage_Use_1000_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto &amp;fit to cell.
        /// </summary>
        public static string HeaderProperty_Auto_Fit_To_Cell {
            get {
                return ResourceManager.GetString("HeaderProperty_Auto_Fit_To_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Properties.
        /// </summary>
        public static string HeaderProperty_Caption {
            get {
                return ResourceManager.GetString("HeaderProperty_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Column &amp;Type:.
        /// </summary>
        public static string HeaderProperty_Default_Column_Type {
            get {
                return ResourceManager.GetString("HeaderProperty_Default_Column_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel &amp;Width:.
        /// </summary>
        public static string HeaderProperty_Panel_Width {
            get {
                return ResourceManager.GetString("HeaderProperty_Panel_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Text:.
        /// </summary>
        public static string HeaderProperty_Text {
            get {
                return ResourceManager.GetString("HeaderProperty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text &amp;Color:.
        /// </summary>
        public static string HeaderProperty_Text_Color {
            get {
                return ResourceManager.GetString("HeaderProperty_Text_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Horizontal_Alignment_Center {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed (Indent).
        /// </summary>
        public static string Horizontal_Alignment_Distributed {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Distributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Horizontal_Alignment_General {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Horizontal_Alignment_Left {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Horizontal_Alignment_Right {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://reogrid.net/.
        /// </summary>
        public static string HP_Homepage {
            get {
                return ResourceManager.GetString("HP_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://reogrid.net/document.
        /// </summary>
        public static string HP_Homepage_Document {
            get {
                return ResourceManager.GetString("HP_Homepage_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        public static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tool Name.
        /// </summary>
        public static string Invalid_Tool_Name {
            get {
                return ResourceManager.GetString("Invalid_Tool_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Color:.
        /// </summary>
        public static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cells.
        /// </summary>
        public static string Menu_Cells {
            get {
                return ResourceManager.GetString("Menu_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Merge Cells.
        /// </summary>
        public static string Menu_Cells_Merge_Cells {
            get {
                return ResourceManager.GetString("Menu_Cells_Merge_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unmerge Cells.
        /// </summary>
        public static string Menu_Cells_Unmerge_Cells {
            get {
                return ResourceManager.GetString("Menu_Cells_Unmerge_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Cells &amp;Type.
        /// </summary>
        public static string Menu_Change_Cells_Type {
            get {
                return ResourceManager.GetString("Menu_Change_Cells_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ut.
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Menu_Edit_Clear {
            get {
                return ResourceManager.GetString("Menu_Edit_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Cell Style.
        /// </summary>
        public static string Menu_Edit_Focus_Cell_Style {
            get {
                return ResourceManager.GetString("Menu_Edit_Focus_Cell_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        public static string Menu_Edit_Readonly {
            get {
                return ResourceManager.GetString("Menu_Edit_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Last &amp;Action.
        /// </summary>
        public static string Menu_Edit_Repeat_Last_Action {
            get {
                return ResourceManager.GetString("Menu_Edit_Repeat_Last_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        public static string Menu_Edit_Select_All {
            get {
                return ResourceManager.GetString("Menu_Edit_Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Selection.
        /// </summary>
        public static string Menu_Edit_Selection {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag To &amp;Fill Serial.
        /// </summary>
        public static string Menu_Edit_Selection_Drag_To_Fill_Serial {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Drag_To_Fill_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Drag To Move Content.
        /// </summary>
        public static string Menu_Edit_Selection_Drag_To_Move_Content {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Drag_To_Move_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection &amp;Mode.
        /// </summary>
        public static string Menu_Edit_Selection_Mode {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Menu_Edit_Selection_Mode_Cell {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Menu_Edit_Selection_Mode_Column {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Menu_Edit_Selection_Mode_None {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Range (Default).
        /// </summary>
        public static string Menu_Edit_Selection_Mode_Range {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Menu_Edit_Selection_Mode_Row {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Move Direction.
        /// </summary>
        public static string Menu_Edit_Selection_Move_Direction {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Move_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Down.
        /// </summary>
        public static string Menu_Edit_Selection_Move_Direction_Down {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Move_Direction_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Right (Default).
        /// </summary>
        public static string Menu_Edit_Selection_Move_Direction_Right {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Move_Direction_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection S&amp;tyle.
        /// </summary>
        public static string Menu_Edit_Selection_Style {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Solid Rectangle.
        /// </summary>
        public static string Menu_Edit_Selection_Style_Default {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Focus Rectangle.
        /// </summary>
        public static string Menu_Edit_Selection_Style_Focus_Rect {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style_Focus_Rect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Menu_Edit_Selection_Style_None {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit RGF &amp;XML....
        /// </summary>
        public static string Menu_File_Edit_RGF_XML {
            get {
                return ResourceManager.GetString("Menu_File_Edit_RGF_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As &amp;CSV....
        /// </summary>
        public static string Menu_File_Export_As_CSV {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Current Worksheet....
        /// </summary>
        public static string Menu_File_Export_As_CSV_Current_Worksheet {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_CSV_Current_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected Range....
        /// </summary>
        public static string Menu_File_Export_As_CSV_Selected_Range {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_CSV_Selected_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As &amp;HTML....
        /// </summary>
        public static string Menu_File_Export_As_HTML {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;Window....
        /// </summary>
        public static string Menu_File_New_Window {
            get {
                return ResourceManager.GetString("Menu_File_New_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        public static string Menu_File_Print {
            get {
                return ResourceManager.GetString("Menu_File_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print P&amp;review....
        /// </summary>
        public static string Menu_File_Print_Preview {
            get {
                return ResourceManager.GetString("Menu_File_Print_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Se&amp;ttings....
        /// </summary>
        public static string Menu_File_Print_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Print_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As....
        /// </summary>
        public static string Menu_File_Save_As {
            get {
                return ResourceManager.GetString("Menu_File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Format Cells....
        /// </summary>
        public static string Menu_Format_Cells {
            get {
                return ResourceManager.GetString("Menu_Format_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Formula.
        /// </summary>
        public static string Menu_Formula {
            get {
                return ResourceManager.GetString("Menu_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Auto Function.
        /// </summary>
        public static string Menu_Formula_Auto_Function {
            get {
                return ResourceManager.GetString("Menu_Formula_Auto_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define &amp;Name....
        /// </summary>
        public static string Menu_Formula_Define_Name {
            get {
                return ResourceManager.GetString("Menu_Formula_Define_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp;Manager....
        /// </summary>
        public static string Menu_Formula_Name_Manager {
            get {
                return ResourceManager.GetString("Menu_Formula_Name_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Worksheet.
        /// </summary>
        public static string Menu_Formula_Recalculate_Worksheet {
            get {
                return ResourceManager.GetString("Menu_Formula_Recalculate_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Trace Arrows.
        /// </summary>
        public static string Menu_Formula_Remove_Trace_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All &amp;Arrows.
        /// </summary>
        public static string Menu_Formula_Remove_Trace_Arrows_Remove_All_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows_Remove_All_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &amp;Dependent Arrows.
        /// </summary>
        public static string Menu_Formula_Remove_Trace_Arrows_Remove_Dependent_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows_Remove_Dependent_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &amp;Precedent Arrows.
        /// </summary>
        public static string Menu_Formula_Remove_Trace_Arrows_Remove_Precedent_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows_Remove_Precedent_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Suspend Reference Updates.
        /// </summary>
        public static string Menu_Formula_Suspend_Reference_Updates {
            get {
                return ResourceManager.GetString("Menu_Formula_Suspend_Reference_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace &amp;Dependents.
        /// </summary>
        public static string Menu_Formula_Trace_Dependents {
            get {
                return ResourceManager.GetString("Menu_Formula_Trace_Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace &amp;Precedents.
        /// </summary>
        public static string Menu_Formula_Trace_Precedents {
            get {
                return ResourceManager.GetString("Menu_Formula_Trace_Precedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Group.
        /// </summary>
        public static string Menu_Group {
            get {
                return ResourceManager.GetString("Menu_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Documents....
        /// </summary>
        public static string Menu_Help_Documents {
            get {
                return ResourceManager.GetString("Menu_Help_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Homepage....
        /// </summary>
        public static string Menu_Help_Homepage {
            get {
                return ResourceManager.GetString("Menu_Help_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        public static string Menu_Hide {
            get {
                return ResourceManager.GetString("Menu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Page &amp;Break.
        /// </summary>
        public static string Menu_Insert_Page_Break {
            get {
                return ResourceManager.GetString("Menu_Insert_Page_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string Menu_More {
            get {
                return ResourceManager.GetString("Menu_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Property....
        /// </summary>
        public static string Menu_Property {
            get {
                return ResourceManager.GetString("Menu_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Page Break.
        /// </summary>
        public static string Menu_Remove_Page_Break {
            get {
                return ResourceManager.GetString("Menu_Remove_Page_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Page &amp;Breaks.
        /// </summary>
        public static string Menu_Reset_All_Page_Breaks {
            get {
                return ResourceManager.GetString("Menu_Reset_All_Page_Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc&amp;ript.
        /// </summary>
        public static string Menu_Script {
            get {
                return ResourceManager.GetString("Menu_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &amp;Function....
        /// </summary>
        public static string Menu_Script_Run_Function {
            get {
                return ResourceManager.GetString("Menu_Script_Run_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script &amp;Editor....
        /// </summary>
        public static string Menu_Script_Script_Editor {
            get {
                return ResourceManager.GetString("Menu_Script_Script_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sheet.
        /// </summary>
        public static string Menu_Sheet {
            get {
                return ResourceManager.GetString("Menu_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string Menu_Sheet_Clear_Filter {
            get {
                return ResourceManager.GetString("Menu_Sheet_Clear_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filter.
        /// </summary>
        public static string Menu_Sheet_Filter {
            get {
                return ResourceManager.GetString("Menu_Sheet_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Group.
        /// </summary>
        public static string Menu_Sheet_Group {
            get {
                return ResourceManager.GetString("Menu_Sheet_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group &amp;Columns.
        /// </summary>
        public static string Menu_Sheet_Group_Columns {
            get {
                return ResourceManager.GetString("Menu_Sheet_Group_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group &amp;Rows.
        /// </summary>
        public static string Menu_Sheet_Group_Rows {
            get {
                return ResourceManager.GetString("Menu_Sheet_Group_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        public static string Menu_Sheet_Insert {
            get {
                return ResourceManager.GetString("Menu_Sheet_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resize....
        /// </summary>
        public static string Menu_Sheet_Resize {
            get {
                return ResourceManager.GetString("Menu_Sheet_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        public static string Menu_Sheet_Settings {
            get {
                return ResourceManager.GetString("Menu_Sheet_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string Menu_Sheet_Ungroup {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Columns.
        /// </summary>
        public static string Menu_Sheet_Ungroup_All_Columns {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_All_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rows.
        /// </summary>
        public static string Menu_Sheet_Ungroup_All_Rows {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_All_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Columns.
        /// </summary>
        public static string Menu_Sheet_Ungroup_Selection_Columns {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_Selection_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Rows.
        /// </summary>
        public static string Menu_Sheet_Ungroup_Selection_Rows {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_Selection_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control &amp;Appearance....
        /// </summary>
        public static string Menu_Tools_Control_Appearance {
            get {
                return ResourceManager.GetString("Menu_Tools_Control_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string Menu_Ungroup {
            get {
                return ResourceManager.GetString("Menu_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup All.
        /// </summary>
        public static string Menu_Ungroup_All {
            get {
                return ResourceManager.GetString("Menu_Ungroup_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Unhide.
        /// </summary>
        public static string Menu_Unhide {
            get {
                return ResourceManager.GetString("Menu_Unhide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Components.
        /// </summary>
        public static string Menu_View_Components {
            get {
                return ResourceManager.GetString("Menu_View_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Formula Bar.
        /// </summary>
        public static string Menu_View_Components_FormulaBar {
            get {
                return ResourceManager.GetString("Menu_View_Components_FormulaBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status Bar.
        /// </summary>
        public static string Menu_View_Components_StatusBar {
            get {
                return ResourceManager.GetString("Menu_View_Components_StatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toolbar.
        /// </summary>
        public static string Menu_View_Components_Toolbar {
            get {
                return ResourceManager.GetString("Menu_View_Components_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Freeze To Cell.
        /// </summary>
        public static string Menu_View_Freeze_To_Cell {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze To &amp;Edges.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bottom.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Bottom {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Le&amp;ft.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Bottom_Left {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Bottom_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Ri&amp;ght.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Bottom_Right {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Bottom_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Left.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Left {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Right {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Top.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Top {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top &amp;Left.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Top_Left {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Top_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top &amp;Right.
        /// </summary>
        public static string Menu_View_Freeze_To_Edges_Top_Right {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Top_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze.
        /// </summary>
        public static string Menu_View_Unfreeze {
            get {
                return ResourceManager.GetString("Menu_View_Unfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Visible.
        /// </summary>
        public static string Menu_View_Visible {
            get {
                return ResourceManager.GetString("Menu_View_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Column Header.
        /// </summary>
        public static string Menu_View_Visible_Column_Header {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Column_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Outline &amp;Panel.
        /// </summary>
        public static string Menu_View_Visible_Column_Outline_Panel {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Column_Outline_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Frozen Line.
        /// </summary>
        public static string Menu_View_Visible_Forzen_Line {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Forzen_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Grid Lines.
        /// </summary>
        public static string Menu_View_Visible_Grid_Lines {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Grid_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Horizontal Scrollbar.
        /// </summary>
        public static string Menu_View_Visible_Horizontal_ScrollBar {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Horizontal_ScrollBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page &amp;Breaks.
        /// </summary>
        public static string Menu_View_Visible_Page_Breaks {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Page_Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Row Header.
        /// </summary>
        public static string Menu_View_Visible_Row_Header {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Row_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row &amp;Outline Panel.
        /// </summary>
        public static string Menu_View_Visible_Row_Outline_Panel {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Row_Outline_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sheet Tab.
        /// </summary>
        public static string Menu_View_Visible_Sheet_Tab {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Sheet_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vertical Scrollbar.
        /// </summary>
        public static string Menu_View_Visible_Vertical_ScrollBar {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Vertical_ScrollBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define named range by specified name. Make sure:
        ///  The name does not begin with a number
        ///  The name does not contain spaces or any invalid characters
        ///  The name is not same as any address of cell and range
        ///  The name is not same as any built-in function names.
        /// </summary>
        public static string Msg_Create_Named_Range_Failed {
            get {
                return ResourceManager.GetString("Msg_Create_Named_Range_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define named range failed.
        /// </summary>
        public static string Msg_Create_Named_Range_Failed_Title {
            get {
                return ResourceManager.GetString("Msg_Create_Named_Range_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected named range?.
        /// </summary>
        public static string Msg_Delete_Named_Range_Confirm {
            get {
                return ResourceManager.GetString("Msg_Delete_Named_Range_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete named range.
        /// </summary>
        public static string Msg_Delete_Named_Range_Confirm_Title {
            get {
                return ResourceManager.GetString("Msg_Delete_Named_Range_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file cannot be found: .
        /// </summary>
        public static string Msg_File_Not_Found {
            get {
                return ResourceManager.GetString("Msg_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the name of range..
        /// </summary>
        public static string Msg_Input_Name_Of_Range {
            get {
                return ResourceManager.GetString("Msg_Input_Name_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of range is invalid..
        /// </summary>
        public static string Msg_Invalid_Address_Of_Range {
            get {
                return ResourceManager.GetString("Msg_Invalid_Address_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file failed: .
        /// </summary>
        public static string Msg_Load_File_Failed {
            get {
                return ResourceManager.GetString("Msg_Load_File_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document contains macro and executable script. Do you want to run the script now?.
        /// </summary>
        public static string Msg_Load_Script_Prompt {
            get {
                return ResourceManager.GetString("Msg_Load_Script_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Script.
        /// </summary>
        public static string Msg_Load_Script_Prompt_Title {
            get {
                return ResourceManager.GetString("Msg_Load_Script_Prompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another range with this name has already existed, are you sure to overwrite it?.
        /// </summary>
        public static string Msg_Named_Range_Overwrite {
            get {
                return ResourceManager.GetString("Msg_Named_Range_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worksheet contained in workbook..
        /// </summary>
        public static string Msg_No_Current_Worksheet {
            get {
                return ResourceManager.GetString("Msg_No_Current_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML edit only available when current file format is ReoGrid Format File (.rgf;*.xml)..
        /// </summary>
        public static string Msg_Only_RGF_Edit_XML {
            get {
                return ResourceManager.GetString("Msg_Only_RGF_Edit_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cannot be performed..
        /// </summary>
        public static string Msg_Operation_Aborted {
            get {
                return ResourceManager.GetString("Msg_Operation_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another outline has already exists at same position..
        /// </summary>
        public static string Msg_Outline_Already_Exist {
            get {
                return ResourceManager.GetString("Msg_Outline_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outline to be added intersects with another one..
        /// </summary>
        public static string Msg_Outline_Intersected {
            get {
                return ResourceManager.GetString("Msg_Outline_Intersected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No outline found at specified position..
        /// </summary>
        public static string Msg_Outline_Not_Found {
            get {
                return ResourceManager.GetString("Msg_Outline_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range to group row or columns. Make sure that the last row or column of worksheet not grouped into any outlines..
        /// </summary>
        public static string Msg_Outline_Out_Of_Range {
            get {
                return ResourceManager.GetString("Msg_Outline_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of outlines reached the maximum number of levels (10)..
        /// </summary>
        public static string Msg_Outline_Too_Much {
            get {
                return ResourceManager.GetString("Msg_Outline_Too_Much", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cannot be performed, range may contains a part of another merged cell..
        /// </summary>
        public static string Msg_Range_Intersection_Exception {
            get {
                return ResourceManager.GetString("Msg_Range_Intersection_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string Msg_Save_Changes {
            get {
                return ResourceManager.GetString("Msg_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor will save current file, continue?.
        /// </summary>
        public static string Msg_Save_File_Immediately {
            get {
                return ResourceManager.GetString("Msg_Save_File_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script execution is not supported by this edition..
        /// </summary>
        public static string Msg_Script_Not_Available {
            get {
                return ResourceManager.GetString("Msg_Script_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code exported into Clipboard..
        /// </summary>
        public static string Msg_Source_Code_Exported_Into_Clipboard {
            get {
                return ResourceManager.GetString("Msg_Source_Code_Exported_Into_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Range Management.
        /// </summary>
        public static string NamedRangeManage_Caption {
            get {
                return ResourceManager.GetString("NamedRangeManage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named ranges:.
        /// </summary>
        public static string NamedRangeManage_Named_Ranges {
            get {
                return ResourceManager.GetString("NamedRangeManage_Named_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New....
        /// </summary>
        public static string NamedRangeManage_New {
            get {
                return ResourceManager.GetString("NamedRangeManage_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        public static string NoColor {
            get {
                return ResourceManager.GetString("NoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先保存模板！！.
        /// </summary>
        public static string OnPreview {
            get {
                return ResourceManager.GetString("OnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReoGrid Editor.
        /// </summary>
        public static string OpenFile_LoadFile_ReoGrid_Editor {
            get {
                return ResourceManager.GetString("OpenFile_LoadFile_ReoGrid_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging Order.
        /// </summary>
        public static string Paging_Order {
            get {
                return ResourceManager.GetString("Paging_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        public static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel.
        /// </summary>
        public static string Pixel {
            get {
                return ResourceManager.GetString("Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust_To.
        /// </summary>
        public static string PrintSettings_Adjust_To {
            get {
                return ResourceManager.GetString("PrintSettings_Adjust_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Settings.
        /// </summary>
        public static string PrintSettings_Caption {
            get {
                return ResourceManager.GetString("PrintSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down, then over.
        /// </summary>
        public static string PrintSettings_Down_Then_Over {
            get {
                return ResourceManager.GetString("PrintSettings_Down_Then_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation:.
        /// </summary>
        public static string PrintSettings_Orientation {
            get {
                return ResourceManager.GetString("PrintSettings_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over, then down.
        /// </summary>
        public static string PrintSettings_Over_Then_Down {
            get {
                return ResourceManager.GetString("PrintSettings_Over_Then_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Size:.
        /// </summary>
        public static string PrintSettings_Paper_Size {
            get {
                return ResourceManager.GetString("PrintSettings_Paper_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % normal size.
        /// </summary>
        public static string PrintSettings_Percent_Normal_Size {
            get {
                return ResourceManager.GetString("PrintSettings_Percent_Normal_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Setup.
        /// </summary>
        public static string PrintSettings_Setup {
            get {
                return ResourceManager.GetString("PrintSettings_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Grid Lines.
        /// </summary>
        public static string PrintSettings_Show_Grid_Lines {
            get {
                return ResourceManager.GetString("PrintSettings_Show_Grid_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Margins.
        /// </summary>
        public static string PrintSettings_Show_Margins {
            get {
                return ResourceManager.GetString("PrintSettings_Show_Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible Settings.
        /// </summary>
        public static string PrintSettings_Visible_Settings {
            get {
                return ResourceManager.GetString("PrintSettings_Visible_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        public static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked (Read-only).
        /// </summary>
        public static string ProtectionPage_Locked {
            get {
                return ResourceManager.GetString("ProtectionPage_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize worksheet.
        /// </summary>
        public static string Resize_Caption {
            get {
                return ResourceManager.GetString("Resize_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Columns:.
        /// </summary>
        public static string Resize_Columns {
            get {
                return ResourceManager.GetString("Resize_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (max: 32,768).
        /// </summary>
        public static string Resize_Columns_Remark {
            get {
                return ResourceManager.GetString("Resize_Columns_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rows:.
        /// </summary>
        public static string Resize_Rows {
            get {
                return ResourceManager.GetString("Resize_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (max: 1,048,576).
        /// </summary>
        public static string Resize_Rows_Remark {
            get {
                return ResourceManager.GetString("Resize_Rows_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Script Function.
        /// </summary>
        public static string RunFunction_Caption {
            get {
                return ResourceManager.GetString("RunFunction_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close this window after running.
        /// </summary>
        public static string RunFunction_Close_This_Window_After_Running {
            get {
                return ResourceManager.GetString("RunFunction_Close_This_Window_After_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Functions:.
        /// </summary>
        public static string RunFunction_Functions {
            get {
                return ResourceManager.GetString("RunFunction_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Run.
        /// </summary>
        public static string RunFunction_Run {
            get {
                return ResourceManager.GetString("RunFunction_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save error: .
        /// </summary>
        public static string Save_Error {
            get {
                return ResourceManager.GetString("Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Workbook.
        /// </summary>
        public static string Save_Workbook {
            get {
                return ResourceManager.GetString("Save_Workbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        public static string Scaling {
            get {
                return ResourceManager.GetString("Scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width.
        /// </summary>
        public static string SetHeaderSize_Caption_Column {
            get {
                return ResourceManager.GetString("SetHeaderSize_Caption_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row height.
        /// </summary>
        public static string SetHeaderSize_Caption_Row {
            get {
                return ResourceManager.GetString("SetHeaderSize_Caption_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        public static string SolidColor {
            get {
                return ResourceManager.GetString("SolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模板名称不能为空.
        /// </summary>
        public static string Template_cant_null {
            get {
                return ResourceManager.GetString("Template_cant_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out.
        /// </summary>
        public static string Time_out {
            get {
                return ResourceManager.GetString("Time_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry it didn&apos;t work out, we&apos;ll try again later..
        /// </summary>
        public static string try_again_later {
            get {
                return ResourceManager.GetString("try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在Execute.
        /// </summary>
        public static string UnExist_Execute_Method {
            get {
                return ResourceManager.GetString("UnExist_Execute_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected parameter.
        /// </summary>
        public static string Unexpected_parameter {
            get {
                return ResourceManager.GetString("Unexpected_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Vertical_Alignment_Bottom {
            get {
                return ResourceManager.GetString("Vertical_Alignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Vertical_Alignment_General {
            get {
                return ResourceManager.GetString("Vertical_Alignment_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string Vertical_Alignment_Middle {
            get {
                return ResourceManager.GetString("Vertical_Alignment_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Vertical_Alignment_Top {
            get {
                return ResourceManager.GetString("Vertical_Alignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request will be processed..
        /// </summary>
        public static string Your_request_will_be_processed {
            get {
                return ResourceManager.GetString("Your_request_will_be_processed", resourceCulture);
            }
        }
    }
}
